.TH PROJUP 1 2022-05-29 LINUX

.SH NAME
projup \- project upstart

.SH SYNOPSIS
.B projup
[\fR\fItype\fR]
[\fR\fIname\fR]

.SH DESCRIPTION
.B projup
creates a basic c binary application of library

.SH OPTIONS
.TP
[\fItype\fR]
makes the project ethier a binary or a library can be \fBbin/lib\fR
.TP
[\fIname\fR]
the name of the project can be a \fBstring\fR

.SH AUTHOR
wolfdesroyer8 <desroyerwolf8@gmail.com>

.SH SEE ALSO
\fByourmom\fR(1)
